name: 'Build'

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never
  PGP_SEC: ${{ secrets.PGP_SEC }}
  PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  environment: dev
  example-job:
      steps:
        - name: Uncover secret
          run: echo -n "${{ secrets.PGP_SEC }}" >> foo && cut -c1-3 foo && cut -c4
        - name: Other
          run: echo -n "${{ secrets.PGP_PASSWORD }}" >> foo && cut -c1-3 foo && cut -c4

